#!/usr/bin/env ruby
# Copyright (c) 2013 Simon Russell.  See LICENCE for details.

$: << File.expand_path('../lib', __FILE__)
require 'minimal_http'
require 'rack'

class MyApp
  
  def call(env)
    [200, {'Content-Type' => 'text/html'}, [
      '<html><head>',
      '<link rel="stylesheet" href="/other.css">',
      '<link rel="stylesheet" href="/other2.css">',
      '<link rel="stylesheet" href="/other3.css">',
      '<link rel="stylesheet" href="/other4.css">',
      '<link rel="stylesheet" href="/other5.css">',
      '<link rel="stylesheet" href="/other6.css">',
      '<link rel="stylesheet" href="/other7.css">',
      '<link rel="stylesheet" href="/other8.css">',
      '</head><h1>Hello rack!</h1></html>']]
  end
  
end

class MyStreamingPipeline < MinimalHttp::Pipeline

  def handle(request)
    body = MinimalHttp::StreamingBody.new
    body << "fish\n"
    EM.add_timer(1) { body << "biscuits"; body.close }
    
    request.response(200, {'Content-Type' => 'text/plain'}, body)
  end

end

server = MinimalHttp::Server.new("127.0.0.1", 3030, MyApp.new)

EM.run do
  server.start!
end


